version: '3.8'

services:

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

  web:
    build:
      context: ../..
      dockerfile: docker/dev/dev.Dockerfile
    command: bash -c "uvicorn app.main:app --host=0.0.0.0"
    # command: bash -c "alembic upgrade head && uvicorn app.main:app --host=0.0.0.0"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../../.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    depends_on:
      - web
    ports:
      - 8000:8000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


volumes:
  db_data:
