services:

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  redis:
    image: redis:latest
    ports:
      - $REDIS_PORT:$REDIS_PORT
    env_file:
      - ../.env

volumes:
  db_data:
