services:

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  web:
    build:
      context: ..
      dockerfile: ./docker/dev.Dockerfile
    command: bash -c "alembic upgrade head && uvicorn app.main:app"
    restart: always
    depends_on:
      - db
    env_file:
      - ../.env

volumes:
  db_data:
