services:

  test_db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=test_password
    volumes:
      - /var/lib/postgresql/data/

  test_scenario:
    container_name: test_scenario
    build:
      context: ../..
      dockerfile: docker/test_scenario/test_scenario.Dockerfile
    command: bash -c "pytest tests/integration_tests/test_scenario.py"
    depends_on:
      - test_db
